name: todoapp_normal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito-sans.ttf

flutter:
  uses-material-design: true
